<a href="https://colab.research.google.com/github/flatplanet/Pytorch-Tutorial-Youtube/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR OPERATIONS**
- Shape and View
- Grabbing Items
- Basic Slices

In [2]:
import torch


In [4]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [22]:
# Differences between shape and view
# https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

In [23]:
# with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [27]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [42]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# Grab a specific item
my_torch7[7]

tensor(7)

In [50]:
# Grab slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [51]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [52]:
# Return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])