<a href="https://colab.research.google.com/github/flatplanet/Pytorch-Tutorial-Youtube/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR MATH OPERATIONS**


*   Add, Subtract, Multiply, Divide, Remainders, Exponents
*   Shorthand and uh, Longhand
*   Reassignment 



In [3]:
import torch
import numpy as np

In [5]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [6]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [9]:
# Addition Longhand 
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [14]:
# Subtraction 
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [15]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [16]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [17]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [18]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [19]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [20]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [21]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [22]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [23]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [25]:
# Reassignment_
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [27]:
tensor_a

tensor([1, 2, 3, 4])

In [33]:
#tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [31]:
tensor_a

tensor([ 6,  8, 10, 12])